usethis::use_readme_md()
usethis::use_mit_license("Finesya")
usethis::use_git()
system("git add .")
system('git commit -m "Initial commit"')
system("git status")
usethis::use_github()
usethis::create_github_token()
gitcreds::gitcreds_set()
system("git push -u origin master")
system('git remote add origin https://github.com/Finesya/PrakKomstatPert8.git')
system("git status")
list.files()
list.files("R")
list.files(all.files = TRUE)
list.files(path = "~", pattern = "\\.Rmd$", recursive = TRUE)
system("git add .")
system('git commit -m "Add Pert 8 Rmd"')
system("git push")
